Added support for converting arbitrary fractions
rugk/unicodify pull request #96
Opened 2024-12-10 16:42 UTC by tdulcet

* Added support for converting arbitrary fractions.
* Added dedicated option for the fraction autocorrections. Maybe fixes #10
  * Also, changed them to not autocorrect if there is a preceding or succeeding slash character, per a bug report.
* Added new Sentence case option.
* Updated to use [`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter).
  * Requires Firefox/Thunderbird 125 or greater.
* Updated to optionally use [`RegExp.escape`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/escape) if available.
  * Requires Firefox/Thunderbird 134.

- [ ] @rugk - The new menu item and options page changes need to be localized.

2024-12-18 00:01 UTC, rugk requested changes
Some minor code style stuff, but generally this looks really cool! Thanks!

2024-12-18 00:01 UTC, rugk commented on src/options/options.html
> +									<label data-i18n="" data-opt-i18n-keep-children for="autocorrectUnicodeFracts">Convert fractions to Unicode characters</label>
Well could you please add the i18n entries to the English `messages.json` and add them here?

This makes it easier to localize later.

2024-12-19 12:14 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +const afractions = Object.freeze({
Both `fractions` variables are used. In order to support the new arbitrary fraction replacements, we need the separate numerator and denominator values for these hardcoded Unicode fraction characters, so I had to add an additional variable.

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +const fractions = Object.freeze(Object.fromEntries(Object.entries(afractions).map(([f, [n, d]]) => [f, n / d])));
Yes, f = fraction, n = numerator and d = denominator (using fractions terminology). I can rename these variables to make this clearer.

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +                        const result = Object.entries(afractions).find(([, [anumerator, adenominator]]) => anumerator === numerator && adenominator === denominator);
Thanks, I will rename these. Using the `a` prefix is just a personal coding style of mine, when two variables mean more or less the same thing.

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +    return Array.from(segmenter.segment(str.replaceAll("\u200D", ""))).length;
Actually, the `\u200D` character was there before on line 145. See the link in the JSDoc comment for why this is needed. Obviously, unit tests would be great, but I did manually test the changes. I hope using `Intl.Segmenter` will fix any existing bugs with this function.

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +        }
Firefox supports selecting multiple ranges at once. I suspect users would not want to perform any autocorrections when there are multiple ranges selected, so this is just a simple sanity check.

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +        const _range = selection.getRangeAt(0);
Yeah, the underscore prefix was here before, but I am not a big fan of it either, so I can remove it. It looks like it was trying to solve a similar problem as my `a` prefixes, as there is already a variable named `range` here.

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +                            label = `${numerator}\u2044${denominator}`;
As far as Unicode is concerned, that character is actually somewhat magical, at least the first time one sees it in action... 🪄

2024-12-19 12:15 UTC, tdulcet commented on src/content_scripts/autocorrect.js
>                  // Numbers regular expression: https://regex101.com/r/7jUaSP/10
Done: https://regex101.com/r/7jUaSP/11

2024-12-19 12:15 UTC, tdulcet commented on src/common/modules/UnicodeTransformationHandler.js
> +    return Array.from(segmenter2.segment(text), ({ segment: [h, ...t] }) => h.toLocaleUpperCase() + t.join("")).join("");
h = head and t = tail.

2024-12-19 12:16 UTC, tdulcet commented on src/common/modules/UnicodeTransformationHandler.js
> +const segmenter2 = new Intl.Segmenter([], { granularity: "sentence" });
Thanks, I will rename these.

2024-12-19 12:16 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +                const fractionRegex = /(?<!\/\d*)(?<numerator>\d+)\/(?<denominator>\d+)$/u;
Done: https://regex101.com/r/RtUMrA/1

2024-12-19 12:16 UTC, tdulcet commented on src/content_scripts/autocorrect.js
> +                            [label] = result;
This is just using the [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) syntax. I find it cleaner than writing the equivalent:
```js
label = result[0];
```

2025-01-10 21:15 UTC, rugk submitted a review, later dismissed

2025-01-10 21:15 UTC, rugk commented on src/content_scripts/autocorrect.js
> +                            [label] = result;
Ah, for one item I find it somewhat strange… there I would prefer the "old" way. But well… just a matter of taste/style.

2025-01-10 21:15 UTC, rugk commented on src/common/modules/UnicodeTransformationHandler.js
> +    return Array.from(segmenter2.segment(text), ({ segment: [h, ...t] }) => h.toLocaleUpperCase() + t.join("")).join("");
Then there is no reaosn not to write ` …Head`  and `…Tail`  etc.

2025-01-16 22:14 UTC, rugk approved these changes

2025-02-20 17:56 UTC, rugk commented
@tdulcet you cold merge this?

2025-02-21 11:56 UTC, merged

2025-04-18 04:52 UTC, Thomas-D-C commented
> * Added new Sentence case option.

Thank you very much. :-)

I suppose the `.` is a mistake.

Why is it placed at the top of `Change casing`, rather than after `Capitalize Each Word`?
I think this would be closer to the general usage frequency, and this would be more consistent to have `Capitalize Each Word` and `Sentence case` grouped, too.

If I'm right, you don't make any punctuation analysis, you capitalize only the 1st word of the selected text.
It's fine for me, I needn't anything more for the moment. :-)
Compared to `Capitalize Each Word`, it will allow me to add some words at the beginning of a sentence, and apply `Capitalize Each Word` on the 1st word and `Lowercase` on the word which was the 1st in one operation. :-)

2025-04-18 05:01 UTC, Thomas-D-C commented
Could you learn me how to submit a `Pull request` please?
Do you prefer I open a new discussion for that purpose?


> I suppose the `.` is a mistake.

I've found how to do that, so I would like to push it if you can help me for that.

> Why is it placed at the top of `Change casing`, rather than after `Capitalize Each Word`?

I've not found how to do that for the moment.

2025-04-18 11:48 UTC, tdulcet commented
> Thank you very much. :-)

No problem, thank you for trying out the feature and providing feedback!

> I suppose the `.` is a mistake.

No mistake. 🙂

> If I'm right, you don't make any punctuation analysis, you capitalize only the 1st word of the selected text.

No, it should capitalize the first word of each sentence in the selected text. It uses the JS [`Intl.Segmenter` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) to determine the sentences. This seems to have a some difficulty after periods when the text is entirely lowercase, but it works great after question and exclamation marks.

> Could you learn me how to submit a `Pull request` please?

Thanks for your interest. There are instructions on how to submit a pull request here: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project. Feel free to open a discussion if you have further questions.

> I've not found how to do that for the moment.

The order of the menu items could be changed here: https://github.com/rugk/unicodify/blob/caf8a2d7cc8892290a64ed21e21cee4663411153/src/common/modules/data/Fonts.js#L135-L141 Pull requests are welcome!

2025-04-20 19:44 UTC, Thomas-D-C commented
> > I suppose the `.` is a mistake.
> 
> No mistake. 🙂

Why?

> 
> > If I'm right, you don't make any punctuation analysis, you capitalize only the 1st word of the selected text.
> 
> No, it should capitalize the first word of each sentence in the selected text. It uses the JS [`Intl.Segmenter` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) to determine the sentences.

OK.
I would have thought it was a waste of time if you did it yourself, but as I understand it, you're using a built-in feature, so it's all good. :-)

However, what do you think about adding uppercase of the word `i`? Maybe it's not a good idea because of different languages ?
It would help me a lot because it's difficult to select.

> This seems to have a some difficulty after periods when the text is entirely lowercase,

As far as I tested it, it has some difficulty after periods, not only when the text is entirely lowercase.


> 
> > Could you learn me how to submit a `Pull request` please?
> 
> Thanks for your interest. There are instructions on how to submit a pull request here: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project.

Thank you. It may take some time for me to understand all of that.

> Feel free to open a discussion if you have further questions.

Thank you very much. :-)

> 
> > I've not found how to do that for the moment.
> 
> The order of the menu items could be changed here:
> 
> [Fonts.js]

Thank you very much. :-)

> Pull requests are welcome!

If I make 1 Pull request containing both the dot and the order, is it easy enough for you to keep only the part you want?

2025-04-21 10:42 UTC, tdulcet commented
> Why?

Sentences usually end in a period. I also used MS Word for inspiration, which uses a period in their menu:
![image](https://github.com/user-attachments/assets/ae6932bb-3c9f-4cae-9ab8-e20cd5fc50a2)

> However, what do you think about adding uppercase of the word `i`? Maybe it's not a good idea because of different languages ?

I have tried to avoid adding language specific features (such as [Title Case](https://en.wikipedia.org/wiki/Title_case)), but feel free to open an issue and we could consider it for a future version. Have you tried double clicking to select single words?

> As far as I tested it, it has some difficulty after periods, not only when the text is entirely lowercase.

Periods can of course occur in the middle of a sentence (e.g. after abbreviations or acronyms), so whatever Unicode library Firefox/Thunderbird is using is probably trying to be smart, maybe too smart. You may want to consider filing a bug with them if you believe it could be improved.

> Thank you very much. :-)

No problem, thanks for your offer to contribute!

> If I make 1 Pull request containing both the dot and the order, is it easy enough for you to keep only the part you want?

Sure, we could always adjust the PR as needed before merging it.

2025-05-04 12:53 UTC, rugk commented
> You may want to consider filing a bug with them if you believe it could be improved.

For reference: The way to go is https://bugzilla.mozilla.org/ – there you can fill them. Be sure to provide a concrete example/as many details as possible.
And link it here, if you do, so we or other curious users of this extension can watch it.

2025-05-04 12:55 UTC, rugk commented
> If I make 1 Pull request containing both the dot and the order, is it easy enough for you to keep only the part you want?

You could BTW make multiple commits, one for each semantic change/feature, but if that is too much work, just do it as you think.

2025-07-16 16:43 UTC, Thomas-D-C commented
> > Could you learn me how to submit a `Pull request` please?
> 
> Thanks for your interest. There are instructions on how to submit a pull request here: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project. Feel free to open a discussion if you have further questions.

I don't have time to investigate this at the moment.
I'll try it later (with the `.` if I have nothing else to do).

> The order of the menu items could be changed here:
> 
> [Fonts.js]

> Pull requests are welcome!

I did this with the web interface provided by github, so I couldn't check that it works: https://github.com/rugk/unicodify/pull/98.
Please tell me if anything is wrong, so I can do better next time. If necessary, tell me if I need to fix anything immediately.

I hope it can be integrated for the 2025 public version, because I would find it long if I had to wait 1 year with this new feature at the top while it's a less basic feature than the others and its behavior is not strictly deterministic (it would be much more annoying than the `.`).

2025-07-17 11:41 UTC, tdulcet commented
> I hope it can be integrated for the 2025 public version

Thanks for the PR!

We can release a new version at anytime when we feel there are enough changes to justify it. I actually was planning to release a new version earlier this month in time for Firefox and Thunderbird 140 ESR, but have been busy... I will try to do so in the next couple of weeks. Your PR should be included.